version: '3.8'

services:
  user-service:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: user-service:latest
    ports:
      - "8085:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - mynetwork
    deploy:
      replicas: 3

  order-service:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: order-service:latest
    ports:
      - "8086:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - user-service
    networks:
      - mynetwork
    deploy:
      replicas: 3

  product-service:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: product-service:latest
    ports:
      - "8087:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - order-service
    networks:
      - mynetwork
    deploy:
      replicas: 3

networks:
  mynetwork:
    driver: bridge
