version: '3.8'

services:
  user-service:
    build:
      context: .
      dockerfile: ./UserService/Dockerfile
    image: user-service:latest
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - mynetwork

  order-service:
    build:
      context: .
      dockerfile: ./OrderService/Dockerfile
    image: order-service:latest
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - user-service
    networks:
      - mynetwork

  product-service:
    build:
      context: .
      dockerfile: ./ProductService/Dockerfile
    image: product-service:latest
    ports:
      - "8083:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - order-service
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
