version: '3.8'

services:
  user-service:
    build:
      context: .
      dockerfile: /Users/vaibhav/my-repos/jumble-shop/user-service/Dockerfile
    image: user-service:latest
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - mynetwork
    deploy:
      replicas: 3

  order-service:
    build:
      context: .
      dockerfile: /Users/vaibhav/my-repos/jumble-shop/order-service/Dockerfile
    image: order-service:latest
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - user-service
    networks:
      - mynetwork
    deploy:
      replicas: 3

  product-service:
    build:
      context: .
      dockerfile: /Users/vaibhav/my-repos/jumble-shop/product-service/Dockerfile
    image: product-service:latest
    ports:
      - "8083:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - order-service
    networks:
      - mynetwork
    deploy:
      replicas: 3

networks:
  mynetwork:
    driver: bridge
